version: '3'
services:
  download:
    image: dbpedia/minimal-download-client:latest
    environment:
      COLLECTION_URI: https://databus.dbpedia.org/kurzum/collections/agro
      TARGET_DIR: /root/data
    volumes:
      - ./downloads:/root/data # has to point to TARGET_DIR
  store:
    image: openlink/virtuoso-opensource-7
    ports: ["${VIRTUOSO_HTTP_PORT}:8890","${VIRTUOSO_ISQL_PORT}:1111"]
    environment:
      DBA_PASSWORD: ${VIRTUOSO_ADMIN_PASSWD}
    volumes:
      - ./virtuoso-db:/opt/virtuoso-opensource/database
      - ./downloads:/usr/share/proj # has to point to STORE_DATA_DIR in 'load'
  load:
    image: dbpedia-virtuoso-loader:latest
    environment:
      STORE_DATA_DIR: /usr/share/proj
      STORE_DBA_PASSWORD: ${VIRTUOSO_ADMIN_PASSWD}
      DATA_DIR: /root/data
      DOMAIN: http://ru.dbpedia.org
    volumes:
      - ./downloads:/root/data # has to point to DATA_DIR
